### ISSUE TITLE
Is it possible to build phpenv versions that aren't covered in this module?

### ISSUE THREAD

**Issue by boztek** [boxen/puppet-php#50]
Such as more recent 5.5 or 5.6 versions directly with phpenv?

**Comment by sambauers** [comment]
This is being explored for version 2 of the module - https://github.com/boxen/puppet-php/pull/56

**Comment by sambauers** [comment]
PR at https://github.com/boxen/puppet-php/pull/57 contains the changes required to build arbitrary versions of PHP.

**Comment by sambauers** [comment]
This is now part of https://github.com/boxen/puppet-php/tree/v2 - suggest we close this.

**Comment by sambauers** [comment]
Now a part of master. Suggest this is closed.

**Comment by mattheath** [comment]
Available with version `2.0.0`
