### ISSUE TITLE
Missing dependencies when including composer on its own.

### ISSUE THREAD

**Issue by rossmcf** [boxen/puppet-php#59]
Hi,

I'm using this module just to install composer. I've had to explicitly add the following dependencies to get it working:

- `wget`
- `autoconf`
- `libtool`
- `pcre`
- `libpng`

Could these be included as part of the package?

Thanks,
Ross

**Comment by sambauers** [comment]
It says you need to add those in the readme at the moment.

**Comment by rossmcf** [comment]
Hi Sam,

Sorry to be pedantic. It says that the modules are required, but not that they'll need to be added manually. This threw me at first because a lot of other modules have a similar statement, and then automatically require their dependencies.

No biggie.

Cheers,
Ross

**Comment by mattheath** [comment]
Hi @rossmcf. This is pretty standard for boxen modules as far as I'm aware, though some may have changed more recently with updates to a couple of the core modules and the puppet standard library. If so, happy to accept a PR to change this. Cheers.
