### ISSUE TITLE
Installing `php::5_4` on clean mac errors

### ISSUE THREAD

**Issue by rossmcf** [boxen/puppet-php#60]
Hi,

We're trying to do the simplest install of php on a clean mac with Yosemite.

The manifest includes `php::5_4` and `mysql` (which seems to sort some other issues), but it blows up part way through the `configure` step for PHP (error below).

Any help you could offer with this would be much appreciated.

Cheers,
Ross

    DESTROYING PHP 5.4.17
    Error: Could not set 'present' on ensure: uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.17> at 120:/opt/boxen/repo/shared/php/manifests/version.pp
    Error: Could not set 'present' on ensure: uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.17> at 120:/opt/boxen/repo/shared/php/manifests/version.pp
    Wrapped exception:
    uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.17>
    Error: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Php_version[5.4.17]/ensure: change from absent to present failed: Could not set 'present' on ensure: uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.17> at 120:/opt/boxen/repo/shared/php/manifests/version.pp
    Notice: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[pear-5.4.17-temp_dir]: Dependency Php_version[5.4.17] has failures: true
    Warning: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[pear-5.4.17-temp_dir]: Skipping because of failed dependencies
    Notice: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[pear-5.4.17-cache_dir]: Dependency Php_version[5.4.17] has failures: true
    Warning: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[pear-5.4.17-cache_dir]: Skipping because of failed dependencies
    Notice: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[pear-5.4.17-download_dir]: Dependency Php_version[5.4.17] has failures: true
    Warning: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[pear-5.4.17-download_dir]: Skipping because of failed dependencies
    Notice: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/File[/opt/boxen/phpenv/versions/5.4.17]: Dependency Php_version[5.4.17] has failures: true
    Warning: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/File[/opt/boxen/phpenv/versions/5.4.17]: Skipping because of failed dependencies
    Notice: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/File[/opt/boxen/phpenv/versions/5.4.17/modules]: Dependency Php_version[5.4.17] has failures: true
    Warning: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/File[/opt/boxen/phpenv/versions/5.4.17/modules]: Skipping because of failed dependencies
    Notice: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[phpenv-rehash-post-install-5.4.17]: Dependency Php_version[5.4.17] has failures: true
    Warning: /Stage[main]/Php::5_4_17/Php::Version[5.4.17]/Exec[phpenv-rehash-post-install-5.4.17]: Skipping because of failed dependencies
    Notice: /Stage[main]/Php::5_4/File[/opt/boxen/phpenv/versions/5.4]: Dependency Php_version[5.4.17] has failures: true
    Warning: /Stage[main]/Php::5_4/File[/opt/boxen/phpenv/versions/5.4]: Skipping because of failed dependencies

**Comment by sambauers** [comment]
Try the v2 branch, and more specifically my latest PR to that branch here - https://github.com/boxen/puppet-php/pull/58

This PR is the same as - https://github.com/sambauers/puppet-php

I think this problem is not happening there.

You will need to switch to the new v2 syntax. In your case:
```
php::version { 5.4: }
```

Otherwise it may just be an upstream configuration issue with the newer builds of PHP on Mac.

**Comment by sambauers** [comment]
v2 branch is now in master. This should probably be closed.

**Comment by outrunthewolf** [comment]
This is still an issue for me.

```sh
Error: Could not set 'present' on ensure: uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.40> at 149:/opt/boxen/repo/shared/php/manifests/version.pp
Error: Could not set 'present' on ensure: uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.40> at 149:/opt/boxen/repo/shared/php/manifests/version.pp
Wrapped exception:
uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.40>
Error: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Php_version[5.4.40]/ensure: change from absent to present failed: Could not set 'present' on ensure: uncaught throw #<RuntimeError: Error occured while configuring PHP 5.4.40> at 149:/opt/boxen/repo/shared/php/manifests/version.pp
Notice: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[pear-5.4.40-temp_dir]: Dependency Php_version[5.4.40] has failures: true
Warning: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[pear-5.4.40-temp_dir]: Skipping because of failed dependencies
Notice: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[phpenv-rehash-post-install-5.4.40]: Dependency Php_version[5.4.40] has failures: true
Warning: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[phpenv-rehash-post-install-5.4.40]: Skipping because of failed dependencies
Notice: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[pear-5.4.40-cache_dir]: Dependency Php_version[5.4.40] has failures: true
Warning: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[pear-5.4.40-cache_dir]: Skipping because of failed dependencies
Notice: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[pear-5.4.40-download_dir]: Dependency Php_version[5.4.40] has failures: true
Warning: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/Exec[pear-5.4.40-download_dir]: Skipping because of failed dependencies
Notice: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/File[/opt/boxen/phpenv/versions/5.4.40]: Dependency Php_version[5.4.40] has failures: true
Warning: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/File[/opt/boxen/phpenv/versions/5.4.40]: Skipping because of failed dependencies
Notice: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/File[/opt/boxen/phpenv/versions/5.4.40/modules]: Dependency Php_version[5.4.40] has failures: true
Warning: /Stage[main]/Projects::Api/Php::Fpm::Pool[projects::api-5.4.40]/Php::Fpm[5.4.40]/Php::Version[5.4.40]/File[/opt/boxen/phpenv/versions/5.4.40/modules]: Skipping because of failed dependencies
```

**Comment by jhenahan** [comment]
Same issue for me.

**Comment by jenslind** [comment]
What version of this puppet are you using? And how does your manifest looks?

**Comment by jhenahan** [comment]
$ puppet --version
    3.7.1

    class projects::proj {

      php::project { 'proj':
        source => 'some-repo',
        mysql => true,
        nginx => "projects/proj/nginx.drupal.conf.erb",
        php => '5.3.29',
      }
    }

**Comment by outrunthewolf** [comment]
Yeah I never managed to get this all working. Even Boxen is pretty flaky in itself at times. I must be doing something massively wrong, because the GH guys swear by it...

**Comment by jenslind** [comment]
What version of OS X? And are you sure you are including all the required modules?
