### ISSUE TITLE
Failed to compile with ssh2 extension

### ISSUE THREAD

**Issue by hussfelt** [boxen/puppet-php#79]
It just gives the error:
"Error: Could not find class ssh2::lib for ..... on node ....local"

https://github.com/boxen/puppet-php/blob/master/manifests/extension/ssh2.pp#L14

**Comment by hussfelt** [comment]
```
#install the php-ssh2 extention
  php::extension::ssh2 { "ssh2 for 5.6.9":
    version   => '1.6.0',
    php     => '5.6.9'
  }
```

**Comment by hussfelt** [comment]
And tried this

```
     php::extension::ssh2 { 'ssh2 for 5.4.10':
       version   => '0.12'
       php       => '5.4.10',
     }
```

**Comment by mattheath** [comment]
Good question. The manifest defines that it requires `ssh2::lib` which is from another boxen module, and looks like it [installs libssh2 from homebrew](https://github.com/boxen/puppet-php/blob/master/manifests/extension/ssh2.pp#L29). I can't see this anywhere though. Hoping @typhonius will know from #51?

**Comment by hussfelt** [comment]
Awesome!
I tried installing it separately, did not work either...

**Comment by mattheath** [comment]
This should be fixed by #80

**Comment by hussfelt** [comment]
:+1:

**Comment by hussfelt** [comment]
@mattheath new release anytime soon? Or should I use master for a while?
Thanks again! :+1:
